### ISSUE TITLE
Server needs to be updated to include itself as a protected file

### ISSUE THREAD

**Issue by coudrew** [mcelearr/JSskillstracker#26]
server_b.js needs to have itself added to `protectedFiles` so

**Comment by samhstn** [comment]
@coudrew What are protectedFiles and why do we need them? Also does the _b mean backend?

**Comment by coudrew** [comment]
protectedFiles was to keep people from going to or downloading parts of the file structure we don't want them to have acces to. There's probably a better way, but I don't know it. and the _b is just cause it was the second version

**Comment by samhstn** [comment]
@coudrew You can .gitignore the files that you dont want to push to github such as API keys. You generally push your server but reference the keys which won't be pushed in a seperate .gitignored file
Check out the dwyl tutorial on this [here](https://github.com/dwyl/learn-environment-variables)
Let me know if you have any more questions about this, otherwise you can close this issue
Also I don't think we are going to use a server (at least for the moment)
